CONTIKI_PROJECT = t2_ctimer
all: $(CONTIKI_PROJECT)

#UIP_CONF_IPV6=1

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include

clean:
	rm -r symbols.* obj_* $(CONTIKI_PROJECT).native contiki-* *.target *.sky
